#!/usr/bin/env bash
# Shared configuration for the SkySpy Proxmox deploy.
# Sourced by provision.sh / deploy.sh. Secrets (PVE token, .env) are NOT stored
# here — pass the token via env, and the generated .env lives beside this file
# (gitignored).

set -euo pipefail

# --- Proxmox target ---
PVE_HOST="${PVE_HOST:-10.42.0.80:8006}"
PVE_NODE="${PVE_NODE:-pve}"
PVE_DATASTORE="${PVE_DATASTORE:-phoenix}"
PVE_TEMPLATE_ID="${PVE_TEMPLATE_ID:-9000}"
# API token: "user@realm!tokenid=secret". Export before running:
#   export PVE_TOKEN='professor_chaos@pve!skyspy=xxxxxxxx-...'
PVE_TOKEN="${PVE_TOKEN:?export PVE_TOKEN='professor_chaos@pve!skyspy=<secret>'}"

# --- New VM ---
VM_ID="${VM_ID:-260}"
VM_NAME="${VM_NAME:-skyspy}"
VM_CORES="${VM_CORES:-4}"
VM_MEMORY="${VM_MEMORY:-8192}"        # MB
VM_DISK_SIZE="${VM_DISK_SIZE:-250G}"
VM_DISK="${VM_DISK:-virtio0}"          # template's boot disk interface

# --- Network (CHAOS_LAB) ---
VM_IP="${VM_IP:-10.42.252.60}"
VM_CIDR="${VM_CIDR:-22}"
VM_GW="${VM_GW:-10.42.252.1}"
VM_DNS="${VM_DNS:-1.1.1.1 1.0.0.1}"
VM_CIUSER="${VM_CIUSER:-skyspy}"

# --- Deploy SSH key (generated by deploy.sh, no hardware key needed) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_KEY="${SSH_KEY:-$SCRIPT_DIR/id_ed25519}"

# --- App ---
REMOTE_DIR="${REMOTE_DIR:-/opt/skyspy}"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- curl helper against the PVE API ---
pve() {
  # usage: pve METHOD /path [curl-args...]
  local method="$1" path="$2"; shift 2
  curl -sk --fail-with-body -X "$method" \
    -H "Authorization: PVEAPIToken=${PVE_TOKEN}" \
    "https://${PVE_HOST}/api2/json${path}" "$@"
}
export -f pve
