# Generated by Django 5.2.10 on 2026-01-27 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyspy', '0006_free_data_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('icao_hex', models.CharField(db_index=True, help_text='ICAO hex code of favorited aircraft', max_length=10)),
                ('registration', models.CharField(blank=True, help_text='Registration at time of favorite (if known)', max_length=20, null=True)),
                ('callsign', models.CharField(blank=True, help_text='Last seen callsign', max_length=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this aircraft', null=True)),
                ('times_seen', models.IntegerField(default=0, help_text='Number of times this aircraft was seen while favorited')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this aircraft was tracked', null=True)),
                ('total_tracking_minutes', models.FloatField(default=0.0, help_text='Total minutes this aircraft was tracked')),
                ('notify_on_detection', models.BooleanField(default=True, help_text='Notify when this aircraft is detected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aircraft_favorites',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('unique_aircraft', models.IntegerField(default=0)),
                ('new_aircraft', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_positions', models.IntegerField(default=0)),
                ('military_count', models.IntegerField(default=0)),
                ('max_distance_nm', models.FloatField(blank=True, null=True)),
                ('max_altitude', models.IntegerField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('aircraft_types', models.JSONField(default=dict)),
                ('operators', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NotableCallsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_type', models.CharField(choices=[('prefix', 'Callsign Prefix'), ('regex', 'Regular Expression'), ('exact', 'Exact Match'), ('contains', 'Contains String')], default='prefix', max_length=20)),
                ('pattern', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('rarity_score', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notable_callsigns',
            },
        ),
        migrations.CreateModel(
            name='NotableRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern_type', models.CharField(choices=[('prefix', 'Registration Prefix'), ('regex', 'Regular Expression'), ('exact', 'Exact Match'), ('contains', 'Contains String')], default='prefix', max_length=20)),
                ('pattern', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('rarity_score', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notable_registrations',
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('max_distance', 'Furthest Aircraft Tracked'), ('max_altitude', 'Highest Altitude Aircraft'), ('max_speed', 'Fastest Aircraft Tracked'), ('longest_session', 'Longest Tracking Session'), ('most_positions', 'Most Positions for Single Aircraft'), ('closest_approach', 'Closest Approach'), ('max_vertical_rate', 'Fastest Climb Rate'), ('max_descent_rate', 'Fastest Descent Rate'), ('earliest_morning', 'Earliest Morning Sighting'), ('latest_night', 'Latest Night Sighting')], db_index=True, max_length=50, unique=True)),
                ('icao_hex', models.CharField(db_index=True, max_length=10)),
                ('callsign', models.CharField(blank=True, max_length=10, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=10, null=True)),
                ('registration', models.CharField(blank=True, max_length=20, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField()),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('achieved_at', models.DateTimeField(db_index=True)),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('previous_icao_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('previous_achieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personal_records',
            },
        ),
        migrations.CreateModel(
            name='RareAircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rarity_score', models.IntegerField(default=5)),
                ('total_produced', models.IntegerField(blank=True, null=True)),
                ('currently_active', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rare_aircraft_types',
            },
        ),
        migrations.CreateModel(
            name='RareSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_type', models.CharField(choices=[('first_hex', 'First Time Hex Seen'), ('first_registration', 'First Time Registration Seen'), ('first_type', 'First Time Aircraft Type Seen'), ('first_operator', 'First Time Operator Seen'), ('rare_type', 'Rare Aircraft Type'), ('government', 'Government/State Aircraft'), ('military', 'Military Aircraft'), ('test_flight', 'Test Flight'), ('special_livery', 'Special Livery'), ('unusual_callsign', 'Unusual Callsign Pattern'), ('notable_registration', 'Notable Registration'), ('air_ambulance', 'Air Ambulance/HEMS'), ('law_enforcement', 'Law Enforcement'), ('firefighting', 'Firefighting Aircraft'), ('historic', 'Historic Aircraft')], db_index=True, max_length=50)),
                ('icao_hex', models.CharField(db_index=True, max_length=10)),
                ('callsign', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('registration', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('aircraft_type', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('sighted_at', models.DateTimeField(db_index=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rarity_score', models.IntegerField(default=1)),
                ('times_seen', models.IntegerField(default=1)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rare_sightings',
            },
        ),
        migrations.CreateModel(
            name='SessionTrackingQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_positions', models.IntegerField(default=0, help_text='Expected positions based on update interval')),
                ('actual_positions', models.IntegerField(default=0, help_text='Actual positions received')),
                ('completeness_score', models.FloatField(default=0.0, help_text='Percentage of expected positions received (0-100)')),
                ('avg_update_rate', models.FloatField(default=0.0, help_text='Average positions per minute during tracking')),
                ('total_gaps', models.IntegerField(default=0, help_text='Number of gaps exceeding threshold')),
                ('max_gap_seconds', models.IntegerField(default=0, help_text='Longest gap between positions (seconds)')),
                ('avg_gap_seconds', models.FloatField(default=0.0, help_text='Average gap between positions (seconds)')),
                ('gap_percentage', models.FloatField(default=0.0, help_text='Percentage of session time in gaps')),
                ('avg_rssi', models.FloatField(blank=True, help_text='Average signal strength during session', null=True)),
                ('rssi_variance', models.FloatField(blank=True, help_text='Variance in signal strength', null=True)),
                ('quality_grade', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='fair', help_text='Overall quality grade', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_tracking_quality',
            },
        ),
        migrations.CreateModel(
            name='SightingStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(choices=[('any_sighting', 'Any Aircraft Sighting'), ('military', 'Military Aircraft Sighting'), ('unique_new', 'New Unique Aircraft'), ('rare_type', 'Rare Aircraft Type'), ('high_altitude', 'High Altitude Sighting (40k+)'), ('long_range', 'Long Range Sighting (100nm+)')], db_index=True, max_length=50, unique=True)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('current_streak_start', models.DateField(blank=True, null=True)),
                ('last_qualifying_date', models.DateField(blank=True, null=True)),
                ('best_streak_days', models.IntegerField(default=0)),
                ('best_streak_start', models.DateField(blank=True, null=True)),
                ('best_streak_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sighting_streaks',
            },
        ),
        migrations.CreateModel(
            name='SpottedAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_hex', models.CharField(db_index=True, max_length=10, unique=True)),
                ('registration', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('aircraft_type', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('operator', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('operator_icao', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_military', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('times_seen', models.IntegerField(default=1)),
                ('total_positions', models.IntegerField(default=0)),
                ('max_distance_nm', models.FloatField(blank=True, null=True)),
                ('max_altitude', models.IntegerField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spotted_aircraft',
            },
        ),
        migrations.CreateModel(
            name='SpottedCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_type', models.CharField(choices=[('operator', 'By Operator/Airline'), ('aircraft_type', 'By Aircraft Type'), ('manufacturer', 'By Manufacturer'), ('country', 'By Country'), ('category', 'By Category')], db_index=True, max_length=50)),
                ('identifier', models.CharField(db_index=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('unique_aircraft', models.IntegerField(default=0)),
                ('total_sightings', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spotted_counts',
            },
        ),
        migrations.AddField(
            model_name='cachednotam',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cachednotam',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cachednotam',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cachedpirep',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cachedpirep',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedpirep',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Deprecated: use visibility field instead'),
        ),
        migrations.AddIndex(
            model_name='cachednotam',
            index=models.Index(fields=['is_archived', 'archived_at'], name='idx_notam_archive'),
        ),
        migrations.AddIndex(
            model_name='cachedpirep',
            index=models.Index(fields=['is_archived', 'archived_at'], name='idx_pirep_archive'),
        ),
        migrations.AddField(
            model_name='aircraftfavorite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who favorited this aircraft (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_aircraft', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notablecallsign',
            index=models.Index(fields=['is_active', 'pattern_type'], name='idx_callsign_active_type'),
        ),
        migrations.AddIndex(
            model_name='notableregistration',
            index=models.Index(fields=['is_active', 'pattern_type'], name='idx_notable_active_type'),
        ),
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['record_type', 'achieved_at'], name='idx_records_type_achieved'),
        ),
        migrations.AddIndex(
            model_name='raresighting',
            index=models.Index(fields=['rarity_type', 'sighted_at'], name='idx_rare_type_sighted'),
        ),
        migrations.AddIndex(
            model_name='raresighting',
            index=models.Index(fields=['icao_hex', 'rarity_type'], name='idx_rare_icao_type'),
        ),
        migrations.AddField(
            model_name='sessiontrackingquality',
            name='session',
            field=models.OneToOneField(help_text='Related aircraft session', on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='skyspy.aircraftsession'),
        ),
        migrations.AddIndex(
            model_name='spottedaircraft',
            index=models.Index(fields=['first_seen'], name='idx_spotted_ac_first'),
        ),
        migrations.AddIndex(
            model_name='spottedaircraft',
            index=models.Index(fields=['last_seen'], name='idx_spotted_ac_last'),
        ),
        migrations.AddIndex(
            model_name='spottedaircraft',
            index=models.Index(fields=['times_seen'], name='idx_spotted_ac_times'),
        ),
        migrations.AddIndex(
            model_name='spottedaircraft',
            index=models.Index(fields=['aircraft_type', 'times_seen'], name='idx_spotted_ac_type_times'),
        ),
        migrations.AddIndex(
            model_name='spottedcount',
            index=models.Index(fields=['count_type', 'unique_aircraft'], name='idx_spotted_type_count'),
        ),
        migrations.AddIndex(
            model_name='spottedcount',
            index=models.Index(fields=['count_type', 'last_seen'], name='idx_spotted_type_last'),
        ),
        migrations.AlterUniqueTogether(
            name='spottedcount',
            unique_together={('count_type', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='aircraftfavorite',
            index=models.Index(fields=['icao_hex', 'created_at'], name='idx_fav_icao_created'),
        ),
        migrations.AddIndex(
            model_name='aircraftfavorite',
            index=models.Index(fields=['user', 'last_seen_at'], name='idx_fav_user_seen'),
        ),
        migrations.AlterUniqueTogether(
            name='aircraftfavorite',
            unique_together={('session_key', 'icao_hex'), ('user', 'icao_hex')},
        ),
        migrations.AddIndex(
            model_name='sessiontrackingquality',
            index=models.Index(fields=['quality_grade', 'completeness_score'], name='idx_quality_grade'),
        ),
    ]
