# Generated by Django 5.2.10 on 2026-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyspy', '0007_add_archive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(max_length=16),
        ),
    ]
