# Generated by Django 5.2.10 on 2026-01-29 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyspy', '0012_cannonball_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='airframesourcedata',
            name='unique_aircraft_source',
        ),
        migrations.RemoveConstraint(
            model_name='cannonballstats',
            name='unique_cannonball_stats_period',
        ),
        migrations.RemoveField(
            model_name='personalrecord',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='raresighting',
            name='session_id',
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records', to='skyspy.aircraftsession'),
        ),
        migrations.AddField(
            model_name='raresighting',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rare_sightings', to='skyspy.aircraftsession'),
        ),
        migrations.AlterField(
            model_name='cannonballalert',
            name='announced',
            field=models.BooleanField(default=False, help_text='Whether TTS announcement was made'),
        ),
        migrations.AlterField(
            model_name='cannonballalert',
            name='notified',
            field=models.BooleanField(default=False, help_text='Whether notification was sent'),
        ),
        migrations.AlterField(
            model_name='cannonballknownaircraft',
            name='agency_state',
            field=models.CharField(blank=True, help_text='US state abbreviation', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='center_lat',
            field=models.FloatField(help_text='Center latitude of pattern'),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='center_lon',
            field=models.FloatField(help_text='Center longitude of pattern'),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0 confidence score'),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When pattern ended (null if ongoing)', null=True),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='pattern_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional pattern-specific data (orbit count, heading changes, etc.)'),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='position_samples',
            field=models.JSONField(blank=True, default=list, help_text='Sample positions used to detect this pattern'),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='radius_nm',
            field=models.FloatField(blank=True, help_text='Radius in nautical miles for circular patterns', null=True),
        ),
        migrations.AlterField(
            model_name='cannonballpattern',
            name='started_at',
            field=models.DateTimeField(help_text='When pattern was first detected'),
        ),
        migrations.AlterField(
            model_name='cannonballsession',
            name='identification_reason',
            field=models.CharField(blank=True, help_text='Why this aircraft was identified as potential LE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cannonballsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional session metadata'),
        ),
        migrations.AlterField(
            model_name='cannonballsession',
            name='urgency_score',
            field=models.FloatField(default=0.0, help_text='0-100 urgency score'),
        ),
        migrations.AlterField(
            model_name='cannonballstats',
            name='top_agencies',
            field=models.JSONField(blank=True, default=list, help_text='List of most frequently detected agencies'),
        ),
        migrations.AlterField(
            model_name='cannonballstats',
            name='top_aircraft',
            field=models.JSONField(blank=True, default=list, help_text='List of most frequently detected aircraft'),
        ),
        migrations.AlterUniqueTogether(
            name='airframesourcedata',
            unique_together={('aircraft_info', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='cannonballstats',
            unique_together={('period_type', 'period_start', 'user')},
        ),
    ]
