# Generated migration to seed initial SystemConfig entries

from django.db import migrations


def seed_config(apps, schema_editor):
    """Seed initial configuration entries from environment variable defaults."""
    SystemConfig = apps.get_model('skyspy', 'SystemConfig')

    configs = [
        # =============================================================================
        # ADS-B Sources
        # =============================================================================
        {
            'key': 'adsb.ultrafeeder_host',
            'category': 'adsb_sources',
            'value': 'ultrafeeder',
            'value_type': 'string',
            'display_name': 'Ultrafeeder Host',
            'description': 'Hostname or IP address of the Ultrafeeder container or server',
            'env_var': 'ULTRAFEEDER_HOST',
            'default_value': 'ultrafeeder',
            'requires_restart': True,
            'sort_order': 1,
        },
        {
            'key': 'adsb.ultrafeeder_port',
            'category': 'adsb_sources',
            'value': '80',
            'value_type': 'integer',
            'display_name': 'Ultrafeeder Port',
            'description': 'HTTP port for Ultrafeeder API',
            'validation_rules': {'min': 1, 'max': 65535},
            'env_var': 'ULTRAFEEDER_PORT',
            'default_value': '80',
            'requires_restart': True,
            'sort_order': 2,
        },
        {
            'key': 'adsb.dump978_host',
            'category': 'adsb_sources',
            'value': 'dump978',
            'value_type': 'string',
            'display_name': 'Dump978 Host',
            'description': 'Hostname for UAT 978MHz receiver (US only)',
            'env_var': 'DUMP978_HOST',
            'default_value': 'dump978',
            'requires_restart': True,
            'sort_order': 3,
        },
        {
            'key': 'adsb.dump978_port',
            'category': 'adsb_sources',
            'value': '80',
            'value_type': 'integer',
            'display_name': 'Dump978 Port',
            'description': 'HTTP port for Dump978 API',
            'validation_rules': {'min': 1, 'max': 65535},
            'env_var': 'DUMP978_PORT',
            'default_value': '80',
            'requires_restart': True,
            'sort_order': 4,
        },
        {
            'key': 'adsb.stream_enabled',
            'category': 'adsb_sources',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'Stream Mode Enabled',
            'description': 'Use SSE/TCP streaming instead of polling for aircraft updates',
            'env_var': 'AIRCRAFT_STREAM_ENABLED',
            'default_value': 'False',
            'requires_restart': True,
            'sort_order': 5,
        },
        {
            'key': 'adsb.stream_mode',
            'category': 'adsb_sources',
            'value': 'sse',
            'value_type': 'string',
            'display_name': 'Stream Mode',
            'description': 'Streaming protocol: sse, tcp, adsbx, or auto',
            'validation_rules': {'choices': ['sse', 'tcp', 'adsbx', 'auto']},
            'env_var': 'AIRCRAFT_STREAM_MODE',
            'default_value': 'sse',
            'requires_restart': True,
            'sort_order': 6,
        },
        {
            'key': 'adsb.stream_host',
            'category': 'adsb_sources',
            'value': '',
            'value_type': 'string',
            'display_name': 'Stream Host',
            'description': 'Hostname for aircraft streaming (defaults to Ultrafeeder host)',
            'env_var': 'AIRCRAFT_STREAM_HOST',
            'default_value': '',
            'requires_restart': True,
            'sort_order': 7,
        },
        {
            'key': 'adsb.stream_port',
            'category': 'adsb_sources',
            'value': '30047',
            'value_type': 'integer',
            'display_name': 'Stream TCP Port',
            'description': 'TCP port for aircraft streaming (net-json-port)',
            'validation_rules': {'min': 1, 'max': 65535},
            'env_var': 'AIRCRAFT_STREAM_PORT',
            'default_value': '30047',
            'requires_restart': True,
            'sort_order': 8,
        },
        {
            'key': 'adsb.stream_sse_port',
            'category': 'adsb_sources',
            'value': '80',
            'value_type': 'integer',
            'display_name': 'Stream SSE Port',
            'description': 'HTTP port for SSE streaming',
            'validation_rules': {'min': 1, 'max': 65535},
            'env_var': 'AIRCRAFT_STREAM_SSE_PORT',
            'default_value': '80',
            'requires_restart': True,
            'sort_order': 9,
        },
        {
            'key': 'adsb.stream_sse_path',
            'category': 'adsb_sources',
            'value': '/v2/sse',
            'value_type': 'string',
            'display_name': 'Stream SSE Path',
            'description': 'URL path for SSE endpoint',
            'env_var': 'AIRCRAFT_STREAM_SSE_PATH',
            'default_value': '/v2/sse',
            'requires_restart': True,
            'sort_order': 10,
        },
        {
            'key': 'adsb.stream_reconnect_delay',
            'category': 'adsb_sources',
            'value': '5',
            'value_type': 'integer',
            'display_name': 'Stream Reconnect Delay',
            'description': 'Seconds to wait before reconnecting after disconnect',
            'validation_rules': {'min': 1, 'max': 60},
            'env_var': 'AIRCRAFT_STREAM_RECONNECT_DELAY',
            'default_value': '5',
            'sort_order': 11,
        },
        {
            'key': 'adsb.stream_batch_ms',
            'category': 'adsb_sources',
            'value': '100',
            'value_type': 'integer',
            'display_name': 'Stream Batch Window (ms)',
            'description': 'Milliseconds to batch incoming stream messages',
            'validation_rules': {'min': 10, 'max': 1000},
            'env_var': 'AIRCRAFT_STREAM_BATCH_MS',
            'default_value': '100',
            'sort_order': 12,
        },
        {
            'key': 'adsb.polling_interval',
            'category': 'adsb_sources',
            'value': '1',
            'value_type': 'integer',
            'display_name': 'Polling Interval (sec)',
            'description': 'Seconds between aircraft data polls (when not streaming)',
            'validation_rules': {'min': 1, 'max': 60},
            'env_var': 'POLLING_INTERVAL',
            'default_value': '1',
            'sort_order': 13,
        },
        {
            'key': 'adsb.db_store_interval',
            'category': 'adsb_sources',
            'value': '5',
            'value_type': 'integer',
            'display_name': 'DB Store Interval (sec)',
            'description': 'Seconds between storing aircraft positions to database',
            'validation_rules': {'min': 1, 'max': 300},
            'env_var': 'DB_STORE_INTERVAL',
            'default_value': '5',
            'sort_order': 14,
        },
        {
            'key': 'adsb.session_timeout_minutes',
            'category': 'adsb_sources',
            'value': '30',
            'value_type': 'integer',
            'display_name': 'Session Timeout (min)',
            'description': 'Minutes before an aircraft session is considered ended',
            'validation_rules': {'min': 5, 'max': 120},
            'env_var': 'SESSION_TIMEOUT_MINUTES',
            'default_value': '30',
            'sort_order': 15,
        },

        # =============================================================================
        # Location
        # =============================================================================
        {
            'key': 'location.feeder_lat',
            'category': 'location',
            'value': '47.9377',
            'value_type': 'float',
            'display_name': 'Feeder Latitude',
            'description': 'Latitude of your ADS-B receiver location',
            'validation_rules': {'min': -90, 'max': 90},
            'env_var': 'FEEDER_LAT',
            'default_value': '47.9377',
            'sort_order': 1,
        },
        {
            'key': 'location.feeder_lon',
            'category': 'location',
            'value': '-121.9687',
            'value_type': 'float',
            'display_name': 'Feeder Longitude',
            'description': 'Longitude of your ADS-B receiver location',
            'validation_rules': {'min': -180, 'max': 180},
            'env_var': 'FEEDER_LON',
            'default_value': '-121.9687',
            'sort_order': 2,
        },

        # =============================================================================
        # Safety Monitoring
        # =============================================================================
        {
            'key': 'safety.monitoring_enabled',
            'category': 'safety',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'Safety Monitoring Enabled',
            'description': 'Enable safety event detection and alerts',
            'env_var': 'SAFETY_MONITORING_ENABLED',
            'default_value': 'True',
            'sort_order': 1,
        },
        {
            'key': 'safety.vs_change_threshold',
            'category': 'safety',
            'value': '2000',
            'value_type': 'integer',
            'display_name': 'VS Change Threshold (ft/min)',
            'description': 'Vertical speed change threshold for safety alerts',
            'validation_rules': {'min': 500, 'max': 10000},
            'env_var': 'SAFETY_VS_CHANGE_THRESHOLD',
            'default_value': '2000',
            'sort_order': 2,
        },
        {
            'key': 'safety.vs_extreme_threshold',
            'category': 'safety',
            'value': '9000',
            'value_type': 'integer',
            'display_name': 'VS Extreme Threshold (ft/min)',
            'description': 'Extreme vertical speed threshold for critical alerts',
            'validation_rules': {'min': 2000, 'max': 20000},
            'env_var': 'SAFETY_VS_EXTREME_THRESHOLD',
            'default_value': '9000',
            'sort_order': 3,
        },
        {
            'key': 'safety.proximity_nm',
            'category': 'safety',
            'value': '0.5',
            'value_type': 'float',
            'display_name': 'Proximity Alert Distance (nm)',
            'description': 'Distance threshold for aircraft proximity alerts',
            'validation_rules': {'min': 0.1, 'max': 5.0},
            'env_var': 'SAFETY_PROXIMITY_NM',
            'default_value': '0.5',
            'sort_order': 4,
        },
        {
            'key': 'safety.altitude_diff_ft',
            'category': 'safety',
            'value': '500',
            'value_type': 'integer',
            'display_name': 'Altitude Diff Threshold (ft)',
            'description': 'Altitude difference threshold for proximity detection',
            'validation_rules': {'min': 100, 'max': 2000},
            'env_var': 'SAFETY_ALTITUDE_DIFF_FT',
            'default_value': '500',
            'sort_order': 5,
        },
        {
            'key': 'safety.closure_rate_kt',
            'category': 'safety',
            'value': '200',
            'value_type': 'float',
            'display_name': 'Closure Rate Threshold (kt)',
            'description': 'Closure rate threshold for converging aircraft',
            'validation_rules': {'min': 50, 'max': 500},
            'env_var': 'SAFETY_CLOSURE_RATE_KT',
            'default_value': '200',
            'sort_order': 6,
        },
        {
            'key': 'safety.tcas_vs_threshold',
            'category': 'safety',
            'value': '1500',
            'value_type': 'integer',
            'display_name': 'TCAS VS Threshold (ft/min)',
            'description': 'VS threshold for potential TCAS RA detection',
            'validation_rules': {'min': 500, 'max': 5000},
            'env_var': 'SAFETY_TCAS_VS_THRESHOLD',
            'default_value': '1500',
            'sort_order': 7,
        },

        # =============================================================================
        # Alerts
        # =============================================================================
        {
            'key': 'alerts.proximity_nm',
            'category': 'alerts',
            'value': '5.0',
            'value_type': 'float',
            'display_name': 'Default Proximity Alert (nm)',
            'description': 'Default distance for proximity alerts',
            'validation_rules': {'min': 0.5, 'max': 100},
            'env_var': 'PROXIMITY_ALERT_NM',
            'default_value': '5.0',
            'sort_order': 1,
        },
        {
            'key': 'alerts.watch_icao_list',
            'category': 'alerts',
            'value': '',
            'value_type': 'string',
            'display_name': 'Watch ICAO List',
            'description': 'Comma-separated list of ICAO hex codes to watch',
            'env_var': 'WATCH_ICAO_LIST',
            'default_value': '',
            'sort_order': 2,
        },
        {
            'key': 'alerts.watch_flight_list',
            'category': 'alerts',
            'value': '',
            'value_type': 'string',
            'display_name': 'Watch Flight List',
            'description': 'Comma-separated list of callsigns/flight numbers to watch',
            'env_var': 'WATCH_FLIGHT_LIST',
            'default_value': '',
            'sort_order': 3,
        },
        {
            'key': 'alerts.alert_military',
            'category': 'alerts',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'Alert on Military Aircraft',
            'description': 'Enable alerts for detected military aircraft',
            'env_var': 'ALERT_MILITARY',
            'default_value': 'True',
            'sort_order': 4,
        },
        {
            'key': 'alerts.alert_emergency',
            'category': 'alerts',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'Alert on Emergency',
            'description': 'Enable alerts for emergency squawk codes (7500, 7600, 7700)',
            'env_var': 'ALERT_EMERGENCY',
            'default_value': 'True',
            'sort_order': 5,
        },

        # =============================================================================
        # ACARS
        # =============================================================================
        {
            'key': 'acars.enabled',
            'category': 'acars',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'ACARS Enabled',
            'description': 'Enable ACARS message decoding and display',
            'env_var': 'ACARS_ENABLED',
            'default_value': 'True',
            'sort_order': 1,
        },
        {
            'key': 'acars.acars_port',
            'category': 'acars',
            'value': '5555',
            'value_type': 'integer',
            'display_name': 'ACARS UDP Port',
            'description': 'UDP port for ACARS messages from acarsdec',
            'validation_rules': {'min': 1, 'max': 65535},
            'env_var': 'ACARS_PORT',
            'default_value': '5555',
            'requires_restart': True,
            'sort_order': 2,
        },
        {
            'key': 'acars.vdlm2_port',
            'category': 'acars',
            'value': '5556',
            'value_type': 'integer',
            'display_name': 'VDL Mode 2 UDP Port',
            'description': 'UDP port for VDL Mode 2 messages from vdlm2dec',
            'validation_rules': {'min': 1, 'max': 65535},
            'env_var': 'VDLM2_PORT',
            'default_value': '5556',
            'requires_restart': True,
            'sort_order': 3,
        },

        # =============================================================================
        # Storage
        # =============================================================================
        {
            'key': 'storage.photo_cache_enabled',
            'category': 'storage',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'Photo Cache Enabled',
            'description': 'Enable caching of aircraft photos locally',
            'env_var': 'PHOTO_CACHE_ENABLED',
            'default_value': 'True',
            'sort_order': 1,
        },
        {
            'key': 'storage.photo_cache_dir',
            'category': 'storage',
            'value': '/data/photos',
            'value_type': 'string',
            'display_name': 'Photo Cache Directory',
            'description': 'Local directory for cached aircraft photos',
            'env_var': 'PHOTO_CACHE_DIR',
            'default_value': '/data/photos',
            'requires_restart': True,
            'sort_order': 2,
        },
        {
            'key': 'storage.photo_auto_download',
            'category': 'storage',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'Auto-Download Photos',
            'description': 'Automatically download aircraft photos when available',
            'env_var': 'PHOTO_AUTO_DOWNLOAD',
            'default_value': 'True',
            'sort_order': 3,
        },
        {
            'key': 'storage.s3_enabled',
            'category': 'storage',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'S3 Storage Enabled',
            'description': 'Use S3-compatible storage for photos and audio',
            'env_var': 'S3_ENABLED',
            'default_value': 'False',
            'requires_restart': True,
            'sort_order': 4,
        },
        {
            'key': 'storage.s3_bucket',
            'category': 'storage',
            'value': '',
            'value_type': 'string',
            'display_name': 'S3 Bucket Name',
            'description': 'S3 bucket name for storage',
            'env_var': 'S3_BUCKET',
            'default_value': '',
            'sort_order': 5,
        },
        {
            'key': 'storage.s3_region',
            'category': 'storage',
            'value': 'us-east-1',
            'value_type': 'string',
            'display_name': 'S3 Region',
            'description': 'AWS region for S3 bucket',
            'env_var': 'S3_REGION',
            'default_value': 'us-east-1',
            'sort_order': 6,
        },
        {
            'key': 'storage.radio_enabled',
            'category': 'storage',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'Radio Recording Enabled',
            'description': 'Enable storage of radio transmission recordings',
            'env_var': 'RADIO_ENABLED',
            'default_value': 'True',
            'sort_order': 7,
        },
        {
            'key': 'storage.radio_audio_dir',
            'category': 'storage',
            'value': '/data/radio',
            'value_type': 'string',
            'display_name': 'Radio Audio Directory',
            'description': 'Local directory for radio transmission files',
            'env_var': 'RADIO_AUDIO_DIR',
            'default_value': '/data/radio',
            'requires_restart': True,
            'sort_order': 8,
        },
        {
            'key': 'storage.radio_max_file_size_mb',
            'category': 'storage',
            'value': '50',
            'value_type': 'integer',
            'display_name': 'Max Radio File Size (MB)',
            'description': 'Maximum size for individual radio recording files',
            'validation_rules': {'min': 1, 'max': 500},
            'env_var': 'RADIO_MAX_FILE_SIZE_MB',
            'default_value': '50',
            'sort_order': 9,
        },
        {
            'key': 'storage.radio_retention_days',
            'category': 'storage',
            'value': '7',
            'value_type': 'integer',
            'display_name': 'Radio Retention (days)',
            'description': 'Days to retain radio recordings before cleanup',
            'validation_rules': {'min': 1, 'max': 365},
            'env_var': 'RADIO_RETENTION_DAYS',
            'default_value': '7',
            'sort_order': 10,
        },

        # =============================================================================
        # Transcription
        # =============================================================================
        {
            'key': 'transcription.enabled',
            'category': 'transcription',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'Transcription Enabled',
            'description': 'Enable audio transcription service',
            'env_var': 'TRANSCRIPTION_ENABLED',
            'default_value': 'False',
            'sort_order': 1,
        },
        {
            'key': 'transcription.service_url',
            'category': 'transcription',
            'value': '',
            'value_type': 'string',
            'display_name': 'Transcription Service URL',
            'description': 'URL of the transcription service API',
            'env_var': 'TRANSCRIPTION_SERVICE_URL',
            'default_value': '',
            'sort_order': 2,
        },
        {
            'key': 'transcription.whisper_enabled',
            'category': 'transcription',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'Whisper Enabled',
            'description': 'Use local Whisper for transcription',
            'env_var': 'WHISPER_ENABLED',
            'default_value': 'False',
            'sort_order': 3,
        },
        {
            'key': 'transcription.whisper_url',
            'category': 'transcription',
            'value': 'http://whisper:9000',
            'value_type': 'string',
            'display_name': 'Whisper Service URL',
            'description': 'URL of the Whisper transcription service',
            'env_var': 'WHISPER_URL',
            'default_value': 'http://whisper:9000',
            'sort_order': 4,
        },
        {
            'key': 'transcription.atc_whisper_enabled',
            'category': 'transcription',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'ATC Whisper Enabled',
            'description': 'Enable ATC-optimized Whisper transcription',
            'env_var': 'ATC_WHISPER_ENABLED',
            'default_value': 'False',
            'sort_order': 5,
        },
        {
            'key': 'transcription.atc_whisper_max_concurrent',
            'category': 'transcription',
            'value': '2',
            'value_type': 'integer',
            'display_name': 'ATC Whisper Concurrency',
            'description': 'Maximum concurrent ATC transcription tasks',
            'validation_rules': {'min': 1, 'max': 10},
            'env_var': 'ATC_WHISPER_MAX_CONCURRENT',
            'default_value': '2',
            'sort_order': 6,
        },
        {
            'key': 'transcription.atc_whisper_preprocess',
            'category': 'transcription',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'ATC Audio Preprocessing',
            'description': 'Enable audio preprocessing for ATC transcription',
            'env_var': 'ATC_WHISPER_PREPROCESS',
            'default_value': 'True',
            'sort_order': 7,
        },
        {
            'key': 'transcription.atc_whisper_noise_reduce',
            'category': 'transcription',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'ATC Noise Reduction',
            'description': 'Enable noise reduction for ATC audio',
            'env_var': 'ATC_WHISPER_NOISE_REDUCE',
            'default_value': 'True',
            'sort_order': 8,
        },

        # =============================================================================
        # External APIs
        # =============================================================================
        {
            'key': 'external.checkwx_enabled',
            'category': 'external_apis',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'CheckWX Enabled',
            'description': 'Enable CheckWX weather API (3,000 req/day free)',
            'env_var': 'CHECKWX_ENABLED',
            'default_value': 'False',
            'sort_order': 1,
        },
        {
            'key': 'external.checkwx_api_key',
            'category': 'external_apis',
            'value': '',
            'value_type': 'secret',
            'display_name': 'CheckWX API Key',
            'description': 'API key for CheckWX weather service',
            'env_var': 'CHECKWX_API_KEY',
            'default_value': '',
            'is_sensitive': True,
            'sort_order': 2,
        },
        {
            'key': 'external.avwx_enabled',
            'category': 'external_apis',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'AVWX Enabled',
            'description': 'Enable AVWX weather API (unlimited free tier)',
            'env_var': 'AVWX_ENABLED',
            'default_value': 'True',
            'sort_order': 3,
        },
        {
            'key': 'external.avwx_api_key',
            'category': 'external_apis',
            'value': '',
            'value_type': 'secret',
            'display_name': 'AVWX API Key',
            'description': 'API key for AVWX weather service (optional)',
            'env_var': 'AVWX_API_KEY',
            'default_value': '',
            'is_sensitive': True,
            'sort_order': 4,
        },
        {
            'key': 'external.openaip_enabled',
            'category': 'external_apis',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'OpenAIP Enabled',
            'description': 'Enable OpenAIP airspace data',
            'env_var': 'OPENAIP_ENABLED',
            'default_value': 'False',
            'sort_order': 5,
        },
        {
            'key': 'external.openaip_api_key',
            'category': 'external_apis',
            'value': '',
            'value_type': 'secret',
            'display_name': 'OpenAIP API Key',
            'description': 'API key for OpenAIP airspace service',
            'env_var': 'OPENAIP_API_KEY',
            'default_value': '',
            'is_sensitive': True,
            'sort_order': 6,
        },
        {
            'key': 'external.opensky_live_enabled',
            'category': 'external_apis',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'OpenSky Live Enabled',
            'description': 'Enable OpenSky Network live API (4,000 credits/day)',
            'env_var': 'OPENSKY_LIVE_ENABLED',
            'default_value': 'False',
            'sort_order': 7,
        },
        {
            'key': 'external.opensky_username',
            'category': 'external_apis',
            'value': '',
            'value_type': 'string',
            'display_name': 'OpenSky Username',
            'description': 'Username for OpenSky Network',
            'env_var': 'OPENSKY_USERNAME',
            'default_value': '',
            'sort_order': 8,
        },
        {
            'key': 'external.opensky_password',
            'category': 'external_apis',
            'value': '',
            'value_type': 'secret',
            'display_name': 'OpenSky Password',
            'description': 'Password for OpenSky Network',
            'env_var': 'OPENSKY_PASSWORD',
            'default_value': '',
            'is_sensitive': True,
            'sort_order': 9,
        },
        {
            'key': 'external.adsbx_live_enabled',
            'category': 'external_apis',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'ADSBx Live Enabled',
            'description': 'Enable ADS-B Exchange live API via RapidAPI',
            'env_var': 'ADSBX_LIVE_ENABLED',
            'default_value': 'False',
            'sort_order': 10,
        },
        {
            'key': 'external.adsbx_rapidapi_key',
            'category': 'external_apis',
            'value': '',
            'value_type': 'secret',
            'display_name': 'ADSBx RapidAPI Key',
            'description': 'RapidAPI key for ADS-B Exchange',
            'env_var': 'ADSBX_RAPIDAPI_KEY',
            'default_value': '',
            'is_sensitive': True,
            'sort_order': 11,
        },
        {
            'key': 'external.aviationstack_enabled',
            'category': 'external_apis',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'Aviationstack Enabled',
            'description': 'Enable Aviationstack flight schedules (100 req/month free)',
            'env_var': 'AVIATIONSTACK_ENABLED',
            'default_value': 'False',
            'sort_order': 12,
        },
        {
            'key': 'external.aviationstack_api_key',
            'category': 'external_apis',
            'value': '',
            'value_type': 'secret',
            'display_name': 'Aviationstack API Key',
            'description': 'API key for Aviationstack',
            'env_var': 'AVIATIONSTACK_API_KEY',
            'default_value': '',
            'is_sensitive': True,
            'sort_order': 13,
        },

        # =============================================================================
        # Notifications
        # =============================================================================
        {
            'key': 'notifications.apprise_urls',
            'category': 'notifications',
            'value': '',
            'value_type': 'string',
            'display_name': 'Apprise URLs',
            'description': 'Comma-separated Apprise notification URLs',
            'env_var': 'APPRISE_URLS',
            'default_value': '',
            'sort_order': 1,
        },
        {
            'key': 'notifications.cooldown',
            'category': 'notifications',
            'value': '300',
            'value_type': 'integer',
            'display_name': 'Notification Cooldown (sec)',
            'description': 'Minimum seconds between repeated notifications',
            'validation_rules': {'min': 0, 'max': 3600},
            'env_var': 'NOTIFICATION_COOLDOWN',
            'default_value': '300',
            'sort_order': 2,
        },

        # =============================================================================
        # Aircraft Data
        # =============================================================================
        {
            'key': 'aircraft.opensky_db_enabled',
            'category': 'aircraft_data',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'OpenSky Database Enabled',
            'description': 'Use local OpenSky aircraft database for enrichment',
            'env_var': 'OPENSKY_DB_ENABLED',
            'default_value': 'True',
            'sort_order': 1,
        },
        {
            'key': 'aircraft.opensky_db_path',
            'category': 'aircraft_data',
            'value': '/data/opensky/aircraft-database.csv',
            'value_type': 'string',
            'display_name': 'OpenSky Database Path',
            'description': 'Path to OpenSky aircraft database CSV file',
            'env_var': 'OPENSKY_DB_PATH',
            'default_value': '/data/opensky/aircraft-database.csv',
            'requires_restart': True,
            'sort_order': 2,
        },

        # =============================================================================
        # Monitoring
        # =============================================================================
        {
            'key': 'monitoring.prometheus_enabled',
            'category': 'monitoring',
            'value': 'True',
            'value_type': 'boolean',
            'display_name': 'Prometheus Metrics Enabled',
            'description': 'Expose Prometheus metrics at /metrics endpoint',
            'env_var': 'PROMETHEUS_ENABLED',
            'default_value': 'True',
            'sort_order': 1,
        },
        {
            'key': 'monitoring.sentry_dsn',
            'category': 'monitoring',
            'value': '',
            'value_type': 'secret',
            'display_name': 'Sentry DSN',
            'description': 'Sentry Data Source Name for error tracking',
            'env_var': 'SENTRY_DSN',
            'default_value': '',
            'is_sensitive': True,
            'requires_restart': True,
            'sort_order': 2,
        },
        {
            'key': 'monitoring.sentry_environment',
            'category': 'monitoring',
            'value': 'development',
            'value_type': 'string',
            'display_name': 'Sentry Environment',
            'description': 'Environment name for Sentry (development, staging, production)',
            'validation_rules': {'choices': ['development', 'staging', 'production']},
            'env_var': 'SENTRY_ENVIRONMENT',
            'default_value': 'development',
            'requires_restart': True,
            'sort_order': 3,
        },
        {
            'key': 'monitoring.sentry_traces_sample_rate',
            'category': 'monitoring',
            'value': '0.1',
            'value_type': 'float',
            'display_name': 'Sentry Traces Sample Rate',
            'description': 'Percentage of transactions to trace (0.0-1.0)',
            'validation_rules': {'min': 0.0, 'max': 1.0},
            'env_var': 'SENTRY_TRACES_SAMPLE_RATE',
            'default_value': '0.1',
            'requires_restart': True,
            'sort_order': 4,
        },

        # =============================================================================
        # Advanced / Caching
        # =============================================================================
        {
            'key': 'advanced.cache_ttl',
            'category': 'advanced',
            'value': '5',
            'value_type': 'integer',
            'display_name': 'Cache TTL (sec)',
            'description': 'Default cache time-to-live for API responses',
            'validation_rules': {'min': 1, 'max': 3600},
            'env_var': 'CACHE_TTL',
            'default_value': '5',
            'sort_order': 1,
        },
        {
            'key': 'advanced.upstream_api_min_interval',
            'category': 'advanced',
            'value': '60',
            'value_type': 'integer',
            'display_name': 'Upstream API Min Interval (sec)',
            'description': 'Minimum seconds between calls to external APIs',
            'validation_rules': {'min': 1, 'max': 3600},
            'env_var': 'UPSTREAM_API_MIN_INTERVAL',
            'default_value': '60',
            'sort_order': 2,
        },
        {
            'key': 'advanced.llm_enabled',
            'category': 'advanced',
            'value': 'False',
            'value_type': 'boolean',
            'display_name': 'LLM Analysis Enabled',
            'description': 'Enable LLM-powered transcript analysis',
            'env_var': 'LLM_ENABLED',
            'default_value': 'False',
            'sort_order': 3,
        },
        {
            'key': 'advanced.llm_api_url',
            'category': 'advanced',
            'value': 'https://api.openai.com/v1',
            'value_type': 'string',
            'display_name': 'LLM API URL',
            'description': 'URL for LLM API (OpenAI-compatible)',
            'env_var': 'LLM_API_URL',
            'default_value': 'https://api.openai.com/v1',
            'sort_order': 4,
        },
        {
            'key': 'advanced.llm_model',
            'category': 'advanced',
            'value': 'gpt-4o-mini',
            'value_type': 'string',
            'display_name': 'LLM Model',
            'description': 'Model name for LLM analysis',
            'env_var': 'LLM_MODEL',
            'default_value': 'gpt-4o-mini',
            'sort_order': 5,
        },
    ]

    for config in configs:
        SystemConfig.objects.create(**config)


def remove_config(apps, schema_editor):
    """Remove all seeded configuration entries."""
    SystemConfig = apps.get_model('skyspy', 'SystemConfig')
    SystemConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('skyspy', '0014_system_config'),
    ]

    operations = [
        migrations.RunPython(seed_config, remove_config),
    ]
