# Generated by Django 5.2.10 on 2026-02-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyspy', '0015_seed_system_config'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['severity', 'timestamp'], name='idx_safety_events_sev_time'),
        ),
    ]
