# Generated by Django 5.2.10 on 2026-07-15 05:21

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyspy', '0024_safetyevent_cpa_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acarsmessage',
            name='noise_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='cooldown_minutes',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='icao_hex',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='aircraftsession',
            index=models.Index(fields=['icao_hex'], name='idx_sessions_icao_hex'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['enabled', 'owner'], name='idx_alert_rules_enabled'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['icao_hex'], name='idx_notif_log_icao'),
        ),
    ]
