# Generated by Django 5.2.10 on 2026-07-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyspy', '0026_fix_faa_flightcheck_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyevent',
            name='event_type',
            field=models.CharField(choices=[('tcas_ra', 'TCAS Resolution Advisory'), ('tcas_ta', 'TCAS Traffic Advisory'), ('extreme_vs', 'Extreme Vertical Speed'), ('vs_reversal', 'Vertical Speed Reversal'), ('proximity_conflict', 'Proximity Conflict'), ('squawk_hijack', 'Squawk 7500 (Hijack)'), ('squawk_radio_failure', 'Squawk 7600 (Radio Failure)'), ('squawk_emergency', 'Squawk 7700 (Emergency)'), ('emergency_squawk', 'Emergency Squawk (legacy)'), ('7500', 'Squawk 7500 (legacy)'), ('7600', 'Squawk 7600 (legacy)'), ('7700', 'Squawk 7700 (legacy)')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyevent',
            name='severity',
            field=models.CharField(choices=[('info', 'Info (legacy)'), ('low', 'Low'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20),
        ),
    ]
