# Generated by Django 6.0.7 on 2026-07-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skyspy", "0031_safety_extreme_vs_default"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="airframedocument",
            name="idx_airframe_doc_embedding",
        ),
    ]
