# Generated by Django 6.0.7 on 2026-07-21 00:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skyspy", "0047_spatial_geom_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveAircraftPosition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icao_hex", models.CharField(db_index=True, max_length=10, unique=True)),
                ("callsign", models.CharField(blank=True, max_length=10, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("altitude", models.IntegerField(blank=True, null=True)),
                ("track", models.FloatField(blank=True, null=True)),
                ("ground_speed", models.FloatField(blank=True, null=True)),
                ("military", models.BooleanField(default=False)),
                ("emergency", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "live_aircraft_positions",
            },
        ),
    ]
